### ISSUE TITLE
ClassMapper : Unit-tests needs to run & pass

### ISSUE THREAD

**Issue by efyx** [nidium/Nidium#12]

**Comment by paraboul** [comment]
JS unit test are not succesful

**Comment by efyx** [comment]
After merging with the master and fixing some little things, the JS unit-tests pass. We still have the native unit-tests to fix.

**Comment by efyx** [comment]
Native unit-tests are fixed, however for an unknown reason the websocket (client) tests are failing.

**Comment by paraboul** [comment]
The websocket client test depends on https://www.websocket.org/echo.html
Looks like websocket.org was offline.

We should enable a local websocket echo server.

**Comment by efyx** [comment]
What about using : http://autobahn.ws/testsuite/ ?

**Comment by paraboul** [comment]
Yes though I'm not sure how it would integrate in our testsuite.

**Comment by efyx** [comment]
The autobahn testsuite looks a bit too extensive for now. I am going to investigate on a more lightweight solution.
