### ISSUE TITLE
Embeded module lookup

### ISSUE THREAD

**Issue by paraboul** [nidium/Nidium#34]
`require()` doesn't work on `embed://` path. Shouldn't `require()` works with any stream allowing `AllowLocalFileStream`?

Also, Embed directory / builtin, should be added to the lookup chain for modules, so that we can easily create "native" js module.

I was thinking to something like :

`src/Embed/` => regular embedded JS files (or resources) (not modules).
`src/Embed/lib/` => public builtin JS modules

e.g. `require("foo");` would look up to `src/Embed/lib/foo.js` (or whichever virtualization `embed://` is bound to).

**Comment by efyx** [comment]
`embed://` and `require()` should now work as expected in release or dev build.

Fixed by https://github.com/nidium/Nidium/commit/ae63bf82442cb83cbf7e8971dcdaf67b82f348dc (and others https://github.com/nidium/Nidium/compare/0a49401606ca...81bd61a)
