### ISSUE TITLE
Move document.canvas from C++ to JS

### ISSUE THREAD

**Issue by paraboul** [nidium/Nidium#35]
We should create `document.canvas` in JS (probably in the `_onready` handler).
This would allow us to use a `NidiumNode` rather than a raw `Canvas` instance.

Also, `document.documentElement` should alias `document.canvas`

**Comment by efyx** [comment]
Fixed in https://github.com/nidium/Nidium/commit/f5c7c7cc183959bafcf1eb161fa9756af82c40a8
