### ISSUE TITLE
What problem(s) is nidium trying to solve

### ISSUE THREAD

**Issue by andywer** [nidium/Nidium#38]
Hi there!
Seems like you put a lot of effort into this and there is also API documentation and stuff.

I had a quick look over the README and the Getting-started, but I am still puzzled regarding the very basics:

*What problem(s) is Nidium trying to solve*
and *what is the benefit of using Nidium instead of existing Node eco system*

That is the very first thing I am usually interested in. Maybe you can explain it better :)

Cheers

**Comment by paraboul** [comment]
hey,

Indeed, it seems that we're still failing to explain what nidium is trying to achieve.

To put it simply, _nidium aims to expose something close to web technology on an easily hackable environment_.

We're not trying to copy the Web. We want a sandbox where you can experiment new things and not being dependent to blink/webkit (e.g. like Electron does). This allow us to add various optimization and non standard things. Moreover, nidium is small (nidium statically linked with all of its dependencies is about 20 MB).

Also, nidium aim to target a large spectre of device and our short term goal is to run it on low power devices (mobile, rpi, ...)

BTW, it uses SpiderMonkey as its JavaScript engine, and we believe that Mozilla needs some love too!

As you may have read on the README, it's still work in progress and not really usable for real application yet :)

**Comment by andywer** [comment]
Yeah, that's understandable :) Adding this explanation to the README might be helpful to others.

**Comment by paraboul** [comment]
Fixed by https://github.com/nidium/Nidium/commit/85fef16ac5216f4bcee7538797cec68175cd1265
