### ISSUE TITLE
New logging system

### ISSUE THREAD

**Issue by efyx** [nidium/Nidium#44]
Currently nidium/libapenetwork use a lot of printf() for printing debugging information. We need to clean this with a unified API.

## Goals
- Handle different logging level (debug, error, verbose, info) that should be configurable at build time
- Logging backend should be overwritable (so we can either use a bare printf() or nidium logging system)
- Each logged message should have a tag associated, so when debugging we can filter out what we want to see (buildtime and/or runtime)
- Use C code (so it can be used in libapenetwork) and has a C++ wrapper for convenience

## Implementation details
- Use macros or functions ? 
- As an external library or header only file ?

## API proposal
- Proposal 1 :
```
logSetLogger(loggingWrapperFunction)
log("LogTag", kLog_Error, "Print a string %s", str);
// OR
logError("LogTag", "Print a string %s", str);
```
- Proposal 2 :
```
Logger::Set(loggingWrapperFunction);
Logger log("LogTag"); 
log.error("This is an error message");
```

**Comment by verpeteren** [comment]
Here is a first 'draft':
https://github.com/nidium/libapenetwork/tree/new-logging-system.
Any feedback is apriciated.

**Comment by paraboul** [comment]
@verpeteren cool.

First thing : coding style (no space between braces, space instead of tab, etc..)

**Comment by verpeteren** [comment]
I changed the coding style in my forked repo.

**Comment by efyx** [comment]
Would it be better to build this as a third-party library / header file ? So the same code can be shared between nidium and libapenetwork ?

One feedback on the usage of the logger mechanism : 

```C
APE_Log(&logger, APE_Log_error, "tag," "should %s print", "");
```
The call is quite "heavy" to remember, how could we simplify it  ? 
* Use global for the logger reference ? 
* Make the "tag" of the log optional ?
* Make the "log level" of the log optional or use different method for each log level (exemple APE_Log_error, APE_Log_info, ...) ?

**Comment by efyx** [comment]
After a call with @paraboul and @verpeteren here is the decision : 
* Keep the logging system inside libapenetwork, nidium will just setup a macro or wrap the logging call inside a higher level function
* The order of the arguments needs to be changed : 
```c
APE_Log(&logger, "string to print : %s\n", "my string", "log_tag", APE_Log_error);
```
The two last arguments needs to be optional (log tag, and log level)

**Comment by verpeteren** [comment]
From our discussion yesterday, I remembered that 'tag' and 'APE_Log_lvl_t' should go on the last 2 positions and should be optional. Please keep in mind this is 'c' here, not 'c++'.
Please advice, how to proceed with the va_arg arguments? 

1) ditch them, the string needs to be preformatted, no params allowed (and obligated)
2) ditch them, only one param is allowed (and obligated assert not NULL)
3) Keep the order of arguments as is currently in this PR.
4) Do something clever like [NARGS macro](http://stackoverflow.com/questions/23647071/how-to-know-last-argument-of-va-list?answertab=active#tab-top). But what? 
6) Prerender them in another/wrapper function. But what?
7) ..

Please advice

**Comment by efyx** [comment]
Could something like that could work : 

```C
#include <stdio.h>

#define EXPAND_ARGS(...) __VA_ARGS__

#define LOG(logger, args) printf(EXPAND_ARGS args)

#define LOG_TAG(logger, args, tag) \
    printf("[%s]", tag);\
    printf(EXPAND_ARGS args);

#define LOG_LVL(logger, args, tag, lvl) \
    printf("[%s/%d]", tag, lvl);\
    printf(EXPAND_ARGS args);

int main() {
    LOG(NULL, ("hello world\n"));
    LOG(NULL, ("hello world %s\n", "nidium"));
    LOG_TAG(NULL, ("hello world %s\n", "nidium"), "LOG_TAG");
    LOG_LVL(NULL, ("hello world %s\n", "nidium"), "LOG_TAG", 0);
}
```

Here there are three macros, but we could use some [tricks](http://stackoverflow.com/questions/3046889/optional-parameters-with-c-macros) to have "optional" arguments for the macro ?

**Comment by paraboul** [comment]
Well, we should not do something nasty or tricky.

Keep it simple and ditch the optional arg idea.

```APE_Log(&logger, APE_LOG_ERR, "tag," "should %s print", "");```

Please note that the error level should be in uppercase.

Anyway, the C++ wrapper is going to handle optional args etc..

**Comment by efyx** [comment]
Also, I would add some simple "alias" for each log level to reduce the typing overhead (like `APE_Loge(&logger, "tag", "should %s print", "");`)

**Comment by paraboul** [comment]
I'm not sure. What does APE_loge means? I guess you mena APE_logError. I don't see how this reduce typing overhead.

I definitly prefere` APE_log(&logger, APE_LOG_ERR, "dfsdf)`. It's way more eye catching

**Comment by efyx** [comment]
Then we will see how this goes during implementation if it's really needed or not ;)

**Comment by efyx** [comment]
This has landed in master :
- https://github.com/nidium/Nidium/commit/48a98788be4db662643cfac3cecd53f418ea248a
- https://github.com/nidium/Nidium/wiki/Logging
