### ISSUE TITLE
link error: jpeg library missing after skia update

### ISSUE THREAD

**Issue by verpeteren** [nidium/Nidium#49]
```
[DEBUG ] Running gyp. File=/data/Development/nidium/Nidium/gyp/all.gyp Target=None
[INFO  ] Executing make -j12
  LINK(target) ../bin/nidium
/usr/bin/ld: error: cannot find -ljpeg
```

With older versions of skia this was located in `/third-party/.default/skia/out/Release/obj/gyp/libjpeg.a`
It appears that libturbo is used now `third-party/.default/skia/third_party/externals/libjpeg-turbo/release/libturbojpeg.pc.in`

**Comment by efyx** [comment]
Thanks, this has been fixed by commit dd6cd241bfda285c31fb02de9bdd28eed10d2e53
