### ISSUE TITLE
Installing nidium on linux as super user does not work

### ISSUE THREAD

**Issue by Mte90** [nidium/Nidium#52]
I want to try Nidium and installed on my system but after the install when I try to execute `/usr/local/bin/nidium` I get the error is a directory.
The file manager see that as a directory but when I open it I got an error too.

**Comment by efyx** [comment]
This seems to be an issue when installing nidium as a super user. Nidium is indeed installed in `/usr/local/bin/nidium/nidium` but the directory does not have correct rights.

A quick workaround is to `sudo chmod -R o=rx /usr/local/bin/nidium`

**Comment by Mte90** [comment]
wow now is perfect!
I installed as superuser so maybe this fix needs to be added in the installation script :-)

**Comment by efyx** [comment]
Yes definitely :) I have noticed a few other issues too, I'll working on fixing them.

Thanks for trying nidium !

**Comment by Mte90** [comment]
I saw the talk at fosdem and as mozilla volunteers i am very curious :-D

**Comment by Mte90** [comment]
Uhm now my linux machine have problems with file association but I am not sure if is because of the Nidium install but they are all missings.

**Comment by efyx** [comment]
Yes indeed this is the other error I have noticed when installing nidium as a super user

**Comment by Mte90** [comment]
Uh okay do you have any suggestions for fix it? There is a linux command for set again the association? on KDE the list is empty and the run file don't contain the script part for the association as i can see

**Comment by efyx** [comment]
Unfortunately I don't have a quick workaround for now.  But you can run nidium from the command line : 

`/usr/local/bin/nidium/nidium /path/to/file.nml`

It also works with remote NML file : 

`/usr/local/bin/nidium/nidium http://p.nf/hello.nml`

**Comment by Mte90** [comment]
this is not an huge problem but I want to fix all my file association that are completely broken XD

**Comment by efyx** [comment]
I am sorry, I didn't understood that part. 

You can try to run `sudo update-desktop-database` and it should reload all of your file associations

**Comment by efyx** [comment]
So I tried this on an Ubuntu laptop and broke the file association too (and also gnome), what I did to fix the issue was : 
```
sudo update-desktop-database /usr/share/
sudo apt-get install --reinstall shared-mime-info
```

Sorry about that poor experience, we will push a fix ASAP

**Comment by Mte90** [comment]
This worked also for me :-)

**Comment by efyx** [comment]
Glad it worked :)

The commit https://github.com/nidium/Nidium/commit/e087cffc9a95899e8a1cdc847516b1376ab3d9b7 fix the issue
