### ISSUE TITLE
Networking: How to transfer binary data?

### ISSUE THREAD

**Issue by cookiengineer** [nidium/Nidium#61]
I just started to use Nidium and I guess I need help to understand what APIs are available.

Is there a way to transfer binary data over the wire? How is this solved, is there something like a Buffer API similar to node.js or how do you realize the encoding/decoding of binary data into utf8 strings and uint8 integers so that you effectively can modify binary data in the JS context?

**Comment by efyx** [comment]
Hi,

You can use the socket API ( https://www.nidium.com/docs/api/master/Nidium/Socket ) and set the binary flag ( https://www.nidium.com/docs/api/master/Nidium/Socket#Socket.binary ). 

We don't have a `Buffer` API like NodeJS, instead we just use JavaScript ArrayBuffer.

**Comment by cookiengineer** [comment]
That means I basically need to use a Uint8Array on that ArrayBuffer and can write the binary data into it?

**Comment by efyx** [comment]
Yes that's it.

**Comment by cookiengineer** [comment]
Damn, that's genius! Awesome!

(Issue is resolved, I guess)

**Comment by paraboul** [comment]
Also, note that the sender does not need to specify the `binary` property since it's implied by the type of the argument.

Also, if you're using the WebSocket API it's automatically handled by the protocol itself (binary flag on the WebSocket header).

**Comment by cookiengineer** [comment]
@paraboul So I guess you mean the 0x01 vs. 0x02 header in the opcode field?

I was asking because I wanted to port [lychee.js](https://github.com/Artificial-Engineering/lycheejs) to your runtime and write platform adapters for it.

The underlying peer-to-peer WS13-based protocol allows switching roles, masks and all, so that's mostly why I would need a binary buffer or (Uint8Array for that matter) to write to. If you're curious, the network protocol is [this file](https://github.com/Artificial-Engineering/lycheejs/blob/development/libraries/lychee/source/net/protocol/WS.js#L227).

**Comment by paraboul** [comment]
@cookiengineer right.

But looking at the WS.js file, you're reimplementing the WebSocket protocol right?

nidium already supports WebSocket (client and server) out of the box : https://www.nidium.com/docs/api/master/Nidium/WebSocketServer

So IIUC, my guess is that you can directly use this feature instead?

**Comment by cookiengineer** [comment]
Well, not exactly :) I'm using a WebSocket custom subprotocol (with the `Protocol: lycheejs` header) so that I can leverage the awesomeness of peer-to-peer, because WS13 per se is only client/server based.
