### ISSUE TITLE
Nidium-server: AddressSanitizer CHECK failed

### ISSUE THREAD

**Issue by cookiengineer** [nidium/Nidium#67]
When trying to use the provided Nidium server binary, it currently fails on ArchLinux. When googling that error up, there was an already fixed issue related to llvm and clang, but that seems to be fixed for other projects as of now. Upstream libraries already contain the fix in their latest versions: https://bugs.archlinux.org/task/50366

```bash
 ./nidium-server 
==4511==AddressSanitizer CHECK failed: /tmp/buildd/llvm-toolchain-3.5-3.5/projects/compiler-rt/lib/asan/asan_rtl.cc:558 "((!asan_init_is_running && "ASan init calls itself!")) != (0)" (0x0, 0x0)
    <empty stack>
```

Software versions:

- ArchLinux (HEAD / up to date)
- llvm-libs 3.9.1-2
- gcc-libs 6.3.1-2

So, in order to find out what the problem is, I probably need to recompile Nidium-server on my machine. I would guess that the buildbot is a legacy Debian/Ubuntu installation, as many projects have similar troubles with an LTS version that still hasn't merged the upstream fixes for the sanitizer.

I will report back when nidium is recompiled on my machine and tested, so that I can verifiy this is related to your buildbot ^_^

**Comment by paraboul** [comment]
Hey,

I'm also using Archlinux and had this bug some times ago.
IIRC it's a bug in llvm and recent version of the glibc.

https://bugs.llvm.org//show_bug.cgi?id=27310

**Comment by cookiengineer** [comment]
@paraboul Yes, I know. It is fixed some time ago already, which means whatever system is building the provided binaries on the website is outdated and using the unfixed llvm / glibc versions.

**Comment by paraboul** [comment]
Oh right, didn't read properly.

ping @verpeteren

**Comment by verpeteren** [comment]
Buildslave is indeed using debian's stock clang version:

```
clang --version
Debian clang version 3.5.0-10 (tags/RELEASE_350/final) (based on LLVM 3.5.0)
Target: x86_64-pc-linux-gnu
Thread model: posix
```
I 'll see how soon I can upgrade this to a more recent version.

**Comment by efyx** [comment]
The issue is that the nidium-server version shouldn't be packaged with ASAN. I'll look into buildbot to figure out this issue.

**Comment by cookiengineer** [comment]
Just FYI: This is the repo for the docker images and the new buildbot https://github.com/cookiengineer/NidiumBuildbot

**Comment by verpeteren** [comment]
@cookiengineer: there is a fresh nidium-server binary on [the download page](https://www.nidium.com/downloads/). This development build was created with clang 3.9.1.

**Comment by efyx** [comment]
I have fixed the issue with ASAN. Release binary are no longer compiled with ASAN enabled.

This new build works : https://nidium.com/static/downloads/Nidium_server_20170413_154429_b4f34c5eb92f0adfc8aabc6ac12a9a5cae983977_Linux_x86-64.tar.gz

**Comment by cookiengineer** [comment]
Awesome!

**Comment by cookiengineer** [comment]
Just wanted to add this for archive purposes: New builds of nidium-server (0.2-dev) from the website work perfectly fine now.
