### ISSUE TITLE
Easier automate-able downloads

### ISSUE THREAD

**Issue by cookiengineer** [nidium/Nidium#70]
Today I was trying to automate the downloads of the Nidium frontend and server files, but the underlying installer (Makeself) does not allow to skip the license question in the beginning.

My plan is to download the runtimes as binaries, so that they are ready for bundling apps. Currently, I was trying to use a simple `./downloaded.run --quiet --keep --noexec <<< "y"`, but the installer hangs and waits for the `y` on stdin because it needs a second to bootup until it accepts inputs from stdin. Either way, this would be more a hack of a hack.

Is there a way to get a `.tar.gz` file or `.zip` file instead of run/dmg files of Nidium, so that automated packaging scripts can make use of them?

**Comment by efyx** [comment]
We don't have tar.gz/zip available right now, but a possible workaround is to use the `--tar` option of Makeself : 

```
./Nidium_frontend_20170414_221727_3d30951d1d0265b1e56b8db941db1d21d2e7e18e_Linux_x86-64.run --tar xvf
```
This will only extract the content of the archive, then you can run nidium with `dist/nidium` (or move it where you'd like) the `installer.sh` script is only for setting the file association of nml files

Would this work for you ?

**Comment by cookiengineer** [comment]
Awesome, that is exactly what I needed. I was looking in the [makeself](https://github.com/megastep/makeself) README and found exactly the same just in parallel :D

**Comment by verpeteren** [comment]
alternative you could use the [expect(1)](https://linux.die.net/man/1/expect) command.
