### ISSUE TITLE
Demos or Documentation

### ISSUE THREAD

**Issue by EisenbergEffect** [nidium/Nidium#93]
I've installed Nidium but now I have no clue what to do 😄  The Getting Started doc is non-existent and the Examples link doesn't go anywhere. Anything at all would greatly help.

Sidenote: I lead the [Aurelia](http://aurelia.io) project. I watched the presentation on the homepage and saw that it was possible to write Vue.js apps with Nidium. We would really love to see if we can get Aurelia up and running on Nidium. We've also recently started work on a vNext of Aurelia, so if there is anything we can take into account to enable our next version to more smoothly work/integrate with Nidium, we'd like to consider it.

Thanks in advance! This looks super awesome. 🥇

**Comment by paraboul** [comment]
Hey @EisenbergEffect,

Indeed, lot of things are moving internally and the project is still not officially released.
More update should come.

**Comment by EisenbergEffect** [comment]
:)
