### ISSUE TITLE
Awesome project but how to test with binaries ?

### ISSUE THREAD

**Issue by mfaessel** [nidium/Nidium#94]
Nidium is an awesome project !

But i'm trying to test the OSX binaries, it just launch an app with the nidium logo and the header

Do i need to build the latest from source ?

Regards

**Comment by verpeteren** [comment]
You do not need to build from source.

When you start the binary, it loads it's 'welcome' screen. 
Normally you'd start with your application as a command line parameter (e.g. `nidium app.nml`).

The documentation for `.nml` files is a bit sparse at the moment but such a file could look a bit like this: 

```xml
<application>
    <nss>
        app: {
            justifyContent:'space-around',
            alignItems: 'center',
            backgroundColor:'#0f181d'
        },
        btn: {
            backgroundColor:'#0f817d',
            width: "90%"
        }
    </nss>
    <layout class="app">
        <img style="" src="nidium.png"/>
        <button class="btn">
            Hello nidium
        </button>
    </layout>
    <script>
console.log("Hello on the commandline");
    </script>
</application>
```

**Comment by mfaessel** [comment]
@verpeteren thank you for your answer.

Work like a charm in OSX and Ubuntu but it seems that Nidium require <meta></meta> tag in the application code. Correct ? I get a NML error without include it.
