### ISSUE TITLE
Create Android Apk

### ISSUE THREAD

**Issue by mfaessel** [nidium/Nidium#95]
Is there more information about the build process for Android ? and desktop ?

@paraboul talk about an demo app in the youtube video www.nidium.com
but the url seems to be broken http://get.ms/8 

Thank you

**Comment by verpeteren** [comment]
The android demo app is called `nidium kitchen sink` and can be installed directly from the [play store](https://play.google.com/store/apps/details?id=com.nidium.android).

**Comment by mfaessel** [comment]
Thank you @verpeteren for the link
Is source code of the kitchen sink available ?
What about building APK for Android ?
