### ISSUE TITLE
Source code for konstructor.py and other parts are missing.

### ISSUE THREAD

**Issue by StetHD** [nidium/Nidium#97]
is this project active? how can I contribute?
please help it seems some parts are missing, what is konstructor py? it's not in python pip repo and how I can have it?

**Comment by verpeteren** [comment]
Thanks for asking, `konstructor.py` is part of our build system, it is actually in `NidiumTools` repository.
If you follow the steps the [README.md](https://github.com/nidium/Nidium#building-nidium), it should you get up-to-speed right away. 
And yes, it is still python2.7, as it is makes use of the `gyp` and `mozmake` infrastructure
